version: '3.9'

# DEV File

services:
  dev-db:
    image: postgres
    command: ['postgres', '-c', 'log_statement=all']
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
